name: Tests

on:
  workflow_dispatch: # Ahora solo se ejecutará si tú entras y le das al botón a mano

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - name: Tests disabled
        run: echo "Los tests de desarrollo están desactivados. Usa el script run.yml para cazar el servidor."
